version: '3.4'

services:
  renan.glasslewis.webapi:
    image: ${DOCKER_REGISTRY-}renanglasslewiswebapi
    hostname: glasslewis-webapi
    build:
      context: ../../
      dockerfile: ./src/Renan.GlassLewis.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 800:80
   

  renan.glasslewis.mvc:
    image: ${DOCKER_REGISTRY-}renanglasslewismvc
    hostname: glasslewis-mvc
    build:
      context: ../../
      dockerfile: ./src/Renan.GlassLewis.Mvc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 801:80

  renan.glasslewis.sqlserver:
    container_name: glasslewis-sqlserver
    hostname: glasslewis-sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Glass@#2021
        - MSSQL_PID=Express
    ports:
        - 1433:1433
    volumes:
        - .data:/var/opt/mssql/data